### PR TITLE
msm: mdss: Adding interface for supporting destination scaler.

### PR DESCRIPTION
**Pull request by assusdan**

### CODE REVIEW

**Comment by visi0nary** [comment]
Hey, thanks for the PR! Why did you close it?

**Comment by assusdan** [comment]
@visi0nary I want to add more commits.

**Comment by assusdan** [comment]
I'll reopen this later

**Comment by visi0nary** [comment]
Okay, great! I am currently trying to upstream to LA.UM.5.6.xxxx completely (so all those missing symbols should be gone by then). Have you already tried that perhaps?

**Comment by assusdan** [comment]
Oh, so I'll not reopen this, and all my changes would stay in my fork repo, because i'm merging only needed commits.

**Comment by visi0nary** [comment]
Feel free to open it nevertheless :)

**Comment by visi0nary** [comment]
Thanks for contributing btw :)

**Comment by visi0nary** [comment]
I just built with your kernel version but shit hits the fan unfortunately:
from last_kmsg:

mdss_fb_do_ioctl: unsupported ioctl (5413)

So at least we know it's related to framebuffer stuff now. Let's see^^

**Pull request closed without merging**
